services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nextjsdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
